
package viewController.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.7
 * Tue Nov 29 08:01:14 GMT-03:00 2016
 * Generated source version: 3.1.7
 */

@XmlRootElement(name = "executeAction", namespace = "http://viewController/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeAction", namespace = "http://viewController/")

public class ExecuteAction {

    @XmlElement(name = "arg0")
    private communication.Pack arg0;

    public communication.Pack getArg0() {
        return this.arg0;
    }

    public void setArg0(communication.Pack newArg0)  {
        this.arg0 = newArg0;
    }

}

